### PR TITLE
Use config.token and config.aliases if set

### LINKED ISSUE #240: SlackRubyBot.config.token does not work?
I'm working on a Slack bot where I have one subclass of `SlackRubyBot::Commands::Base` per file. I also have my logger and Slack token that gets set within a Rails initializer file. What I have is equivalent to:

```ruby
require 'slack-ruby-bot'
require 'logger'

SlackRubyBot.configure do |config|
  config.token = ENV['MY_SLACK_TOKEN']
  config.logger = Logger.new(STDOUT, level: Logger::INFO)
end

class FirstCommand < SlackRubyBot::Commands::Base
  command 'first' do |client, data, match|
    client.say(text: '1!', channel: data.channel)
  end
end

class SecondCommand < SlackRubyBot::Commands::Base
  command 'second' do |client, data, match|
    client.say(text: '2!', channel: data.channel)
  end
end

class MySlackBot < SlackRubyBot::Bot
end

MySlackBot.run
```

1. Is this a reasonable structure? I didn't see anything in the README or examples to suggest otherwise
2. `config.token` doesn't seem to work. I get the following stack trace when I run my code:

    ```
    $ MY_SLACK_TOKEN=my-token-here bundle exec ruby my_slack_bot.rb
    Traceback (most recent call last):
            7: from my_slack_bot.rb:25:in `<main>'
            6: from /Users/jeff.rabovsky/.gem/ruby/2.6.5/gems/slack-ruby-bot-0.12.0/lib/slack-ruby-bot/bot.rb:6:in `run'
            5: from /Users/jeff.rabovsky/.gem/ruby/2.6.5/gems/slack-ruby-bot-0.12.0/lib/slack-ruby-bot/bot.rb:10:in `instance'
            4: from /Users/jeff.rabovsky/.gem/ruby/2.6.5/gems/slack-ruby-bot-0.12.0/lib/slack-ruby-bot/app.rb:19:in `instance'
            3: from /Users/jeff.rabovsky/.gem/ruby/2.6.5/gems/slack-ruby-bot-0.12.0/lib/slack-ruby-bot/app.rb:19:in `new'
            2: from /Users/jeff.rabovsky/.gem/ruby/2.6.5/gems/slack-ruby-bot-0.12.0/lib/slack-ruby-bot/app.rb:4:in `initialize'
            1: from /Users/jeff.rabovsky/.gem/ruby/2.6.5/gems/slack-ruby-bot-0.12.0/lib/slack-ruby-bot.rb:12:in `configure'
    /Users/jeff.rabovsky/.gem/ruby/2.6.5/gems/slack-ruby-bot-0.12.0/lib/slack-ruby-bot/app.rb:5:in `block in initialize': Missing ENV['SLACK_API_TOKEN']. (RuntimeError)
    ```

    But when I run my code like `SLACK_API_TOKEN=my-token-here bundle exec ruby my_slack_bot.rb` instead, it works as expected
3. It seems odd to have an empty subclass of `SlackRubyBot::Bot`. Is that the right way to combine and run multiple subclasses of `SlackRubyBot::Commands::Base`?

Thanks for your help

### PR DESCRIPTION
**Pull request by wasabigeek**
Fixes #240.

I assumed that setting the config in code would take precedence over an ENV variable.

Will do a separate PR for aliases after this!

### CODE REVIEW

File: lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb [hunk 1]
```diff
@@ -12,4 +15,35 @@
       expect { subject }.to raise_error RuntimeError, "Missing ENV['SLACK_API_TOKEN']."
     end
   end
+
+  context 'when SLACK_API_TOKEN is defined in ENV but not config' do
+    it 'sets config.token from ENV' do
+      allow(ENV).to receive(:[]).and_call_original.at_least(:once)
+      allow(ENV).to receive(:[]).with('SLACK_API_TOKEN').and_return(token)
+      SlackRubyBot.configure { |config| config.token = nil }
```
Comment (wasabigeek) [inline lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb:23]: This pattern diverges from the existing, I do feel it makes the tests more isolated from the setup in spec_helper. What do you think @dblock?

Comment (dblock) [reply lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb:23]: I like it.

**Comment by dblock** [comment]
Let's also allow passing the token in the constructor for `Server` in `options`?

File: lib/slack-ruby-bot/app.rb [hunk 2]
```diff
@@ -4,7 +4,9 @@ module SlackRubyBot
   class App < Server
     def initialize(options = {})
       SlackRubyBot.configure do |config|
```
Comment (dblock) [inline lib/slack-ruby-bot/app.rb:6]: So I think this old code is wrong. We're trying to set a global config token in the constructor for a server. Let's move this code into a class method and rewrite `self.instance`.

```ruby
def self.instance
   @instance ||= begin
        configure!
        new
   end
end
```

Constructor should also take an optional token, this way we can have many server instances with different tokens. It's not used like this, but it makes testing easier and doesn't mix instances and globals?

**Comment by wasabigeek** [comment]
> passing the token in the constructor for Server in options

Stopped short of this, some questions:
- were there any particular use cases you had in mind for letting each Server instance have it's own token? e.g. different slack bots running on the same server, but for the same team (since team would still be a global config, unless we do something there too)?
- it seems like the token doesn't actually get used in Server (it gets passed down to Client, but Client doesn't use it, I suppose because `Slack` requires the config to be set globally), is that intentional? (Though fixing that should probably be a separate PR anyway)

File: lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb [hunk 3]
```diff
@@ -1,15 +1,49 @@
 # frozen_string_literal: true
 
 shared_examples 'a slack ruby bot' do
```
Comment (wasabigeek) [inline lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb:3]: Curious, is the shared example so it can be used by subclasses of Server? What was the thinking behind separating App and Server?

**Comment by dblock** [comment]
> > passing the token in the constructor for Server in options
> 
> ~Stopped short of this~, some questions:
> 
> * were there any particular use cases you had in mind for letting each Server instance have it's own token? e.g. different slack bots running on the same server, but for the same team (since team would still be a global config, unless we do something there too)?

It's more of a best practice thing, we can have a singleton, but not globals where it's unnecessary. I don't have a better scenario, but for testing alone it's worth it IMHO.

> * it seems like the token doesn't actually get used in Server (it gets passed down to Client, but Client doesn't use it, I suppose because `Slack` requires the config to be set globally), is that intentional? (Though fixing that should probably be a separate PR anyway)

We possibly have issues here, but I am not sure. The thing is that most people use this library with slack-ruby-bot-server, that doesn't use any of these globals and creates a bot instance with a token following an OAuth workflow. The globals were a facility to run a single bot for a single team with a token, which is deprecated by slack. Feel free to fix all/some/none! And greatly appreciate it and happy to help.

File: lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb (hunk 3 above)
Comment (dblock) [reply lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb:3]: Exactly. An app is something that builds on top of server and does custom things on hooks.

File: lib/slack-ruby-bot/app.rb [hunk 4]
```diff
@@ -3,26 +3,36 @@
...
     def initialize(options = {})
-      SlackRubyBot.configure do |config|
-        config.token = ENV['SLACK_API_TOKEN'] || raise("Missing ENV['SLACK_API_TOKEN'].")
-        config.aliases = ENV['SLACK_RUBY_BOT_ALIASES'].split(' ') if ENV['SLACK_RUBY_BOT_ALIASES']
-      end
-      Slack.configure do |config|
-        config.token = SlackRubyBot.config.token
-      end
-      super
+      server_options = options.select { |k, _| k.to_sym == :token }
```
Comment (dblock) [inline lib/slack-ruby-bot/app.rb:6]: uhm `server_options = { token: options[:token] }`? Definitely no need to account for a string key in config.

File: CHANGELOG.md [hunk 5]
```diff
@@ -1,6 +1,7 @@
 ### 0.14.1 (Next)
 
 * Your contribution here.
+* [#254](https://github.com/slack-ruby/slack-ruby-bot/pull/254): Allow setting of config.token in initializer - [@wasabigeek](https://github.com/wasabigeek).
```
Comment (dblock) [inline CHANGELOG.md:4]: Quote `config.token`

File: lib/slack-ruby-bot/app.rb [hunk 6]
```diff
@@ -3,26 +3,36 @@
...
     end
 
     private
 
+    def self.configure!
+      SlackRubyBot.configure do |config|
+        config.token ||= ENV['SLACK_API_TOKEN']
+        raise("Missing ENV['SLACK_API_TOKEN'].") if config.token.nil?
+
+        config.aliases = ENV['SLACK_RUBY_BOT_ALIASES'].split(' ') if ENV['SLACK_RUBY_BOT_ALIASES']
```
Comment (dblock) [inline lib/slack-ruby-bot/app.rb:28]: `ENV.key?('SLACK_RUBY_BOT_ALIASES')` maybe?

Generally on whether to check for `.nil?` (like here) or whether it's set: I am of the opinion that someone can do `config.token = nil` and that is _a setting_ and therefore they are attempting to do something specific and we shouldn't overwrite that `via .token ||= ENV['']` for example and raise an error. The user example is someone writing `config.token = ENV['DOES_NOT_EXIST']` and somehow defaulting to `ENV['SLACK_API_TOKEN']` magically would be a bug.

Comment (wasabigeek) [reply lib/slack-ruby-bot/app.rb:28]: I’m thinking I’ll keep the existing code for aliases in this PR for now (this was from copy paste), will be cleaner to look at it separately :) is that ok?

As for the token, didn’t think of that - Does this mean we default to having the ENV variables take precedence? (e.g. replace this only `if ENV.key?`) Else I’m a little uncertain how to handle it without a `||=`.

Comment (dblock) [reply lib/slack-ruby-bot/app.rb:28]: Keep existing: yes.

ENV doesn't take precedence, all I am saying is that there's a difference between `ENV['X']` and `ENV.key?('X')`. The former returns `false` when `ENV['X'] == nil`, but the latter does not. We want the latter.

Comment (wasabigeek) [reply lib/slack-ruby-bot/app.rb:28]: 👌 got it, though technically if both were present, the ENV would take precedence unless they dive into the App instance

File: lib/slack-ruby-bot/app.rb [hunk 7]
```diff
@@ -3,26 +3,36 @@
...
-      SlackRubyBot.configure do |config|
-        config.token = ENV['SLACK_API_TOKEN'] || raise("Missing ENV['SLACK_API_TOKEN'].")
-        config.aliases = ENV['SLACK_RUBY_BOT_ALIASES'].split(' ') if ENV['SLACK_RUBY_BOT_ALIASES']
-      end
-      Slack.configure do |config|
-        config.token = SlackRubyBot.config.token
-      end
-      super
+      server_options = { token: options[:token] }
+      super(server_options)
```
Comment (dblock) [inline lib/slack-ruby-bot/app.rb:7]: So this is `super(options)`, which is basically the same thing. Remove the constructor altogether, the `super`'s constructor works out of the box.

File: lib/slack-ruby-bot/app.rb [hunk 8]
```diff
@@ -3,26 +3,36 @@
...
     end
 
     private
 
+    def self.configure!
+      SlackRubyBot.configure do |config|
+        config.token = ENV['SLACK_API_TOKEN'] if ENV.key?('SLACK_API_TOKEN')
+        raise('Missing Slack API Token.') if config.token.nil?
+
+        config.aliases = ENV['SLACK_RUBY_BOT_ALIASES'].split(' ') if ENV['SLACK_RUBY_BOT_ALIASES']
```
Comment (dblock) [inline lib/slack-ruby-bot/app.rb:28]: `if ENV.key?('SLACK_RUBY_BOT_ALIASES')`

File: lib/slack-ruby-bot/app.rb [hunk 9]
```diff
@@ -3,26 +3,36 @@
...
+        new(token: SlackRubyBot.config.token)
+      end
     end
 
     private
 
+    def self.configure!
+      SlackRubyBot.configure do |config|
+        config.token = ENV['SLACK_API_TOKEN'] if ENV.key?('SLACK_API_TOKEN')
+        raise('Missing Slack API Token.') if config.token.nil?
```
Comment (dblock) [inline lib/slack-ruby-bot/app.rb:26]: `unless config.token.present?` is more idiomatic ruby

File: lib/slack-ruby-bot/app.rb [hunk 10]
```diff
@@ -3,26 +3,36 @@
...
+
+        config.aliases = ENV['SLACK_RUBY_BOT_ALIASES'].split(' ') if ENV['SLACK_RUBY_BOT_ALIASES']
+      end
+      Slack.configure do |config|
+        config.token = SlackRubyBot.config.token
+      end
+    end
+    private_class_method :configure!
```
Comment (dblock) [inline lib/slack-ruby-bot/app.rb:34]: Let's keep it public so users can call it without using a singleton instance? No need to document.

File: lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb [hunk 11]
```diff
@@ -4,12 +4,13 @@
   context 'not configured' do
     before do
       @slack_api_token = ENV.delete('SLACK_API_TOKEN')
+      SlackRubyBot.configure { |config| config.token = nil }
```
Comment (dblock) [inline lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb:7]: Implement or use `reset` for the configuration and reset all these tokens and ENV and restore ENV afterwards in a support/....rb. Like In https://github.com/slack-ruby/slack-ruby-client/blob/7c93cec20b87b38388b8afe092ca5d6adf71e51e/spec/support/token.rb, so we don't have to do it all over the place and always start with a blank configuration.

Comment (wasabigeek) [reply lib/slack-ruby-bot/rspec/support/slack-ruby-bot/it_behaves_like_a_slack_bot.rb:7]: Looks like these are already in:
- https://github.com/slack-ruby/slack-ruby-bot/blob/master/lib/slack-ruby-bot/rspec/support/slack_ruby_bot_configure.rb
- https://github.com/slack-ruby/slack-ruby-bot/blob/master/lib/slack-ruby-bot/rspec/support/slack_api_key.rb

I'll change to use those!
